on: 
  push:
    branches:
    - main  

jobs:
  build-and-deploy:
    name: Build app and deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run:
          # build the app using npm - grabs node_modules library packs needed for the build
          npm install
